logging:
  path: ./logs/
spring:
  data:
    mongodb:
      uri: mongodb://DocTool:123456@120.79.79.151:27017/DocTool?maxPoolSize=50&connectTimeoutMS=30000&socketTimeoutMS=3000
  application:
    name: publicservice-server
  rabbitmq:
    host: 120.79.79.151
    port: 5672
    username: guest
    password: guest
server:
  tomcat:
    uri-encoding: utf-8
#定时任务线程池配置
schedule:
  threadpool:
    corePoolSize: 10
    maxPoolSize: 200
    queueCapacity: 10
websocket:
  MaxTextMessageBufferSize: 8192
  MaxBinaryMessageBufferSize: 8192
redis:
  address: redis://myRedis:123456@120.79.79.151:6379
eureka:
  client:
    service-url:
      DEFAULT_ZONE: http://localhost:8761/eureka/,http://localhost:8762/eureka/,http://localhost:8763/eureka/